services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_horarios
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default

networks:
  default:
    name: proyecto-integrador-de-software_default
    external: true

volumes:
  pgadmin_data:
